/**
 * i18n.js — instant Arabic/English switching.
 */
const dict = {
  en: {
    dashboard:'Dashboard', projects:'Projects', editor:'Editor', materials:'Materials',
    export:'Export', settings:'Settings', newProject:'New Project', importProject:'Import Project',
    recentProjects:'Recent Projects', continueProject:'Continue', noProjects:'No projects yet — create your first one!',
    projectName:'Project Name', create:'Create', cancel:'Cancel', save:'Save', delete:'Delete',
    duplicate:'Duplicate', rename:'Rename', open:'Open', close:'Close', apply:'Apply',
    language:'Language', apiKey:'Gemini API Key', saveKey:'Save Key', testApi:'Test API',
    model:'Model', apiOk:'API connection successful ✓', apiFail:'API test failed',
    keySaved:'API key saved (encrypted locally)', enterKey:'Enter your Gemini API key',
    backgrounds:'Backgrounds', music:'Music', sfx:'Sound Effects', memes:'Memes', images:'Images', videos:'Videos',
    upload:'Upload', uploadFiles:'Drop files here or click to upload', search:'Search', skip:'Skip',
    library:'Library', category:'Category', all:'All',
    preview:'Preview', timeline:'Timeline', properties:'Properties', inspector:'Inspector',
    media:'Media', history:'History', ai:'AI Director', captions:'Captions',
    play:'Play', pause:'Pause', stop:'Stop', split:'Split', undo:'Undo', redo:'Redo',
    zoomIn:'Zoom In', zoomOut:'Zoom Out', fit:'Fit', snap:'Snap', safeArea:'Safe Area',
    position:'Position', scale:'Scale', rotation:'Rotation', opacity:'Opacity',
    transform:'Transform', chromaKey:'Chroma Key', tolerance:'Tolerance', softness:'Edge Softness',
    spill:'Spill Removal', feather:'Feather', blur:'Blur', enabled:'Enabled', keyColor:'Key Color',
    volume:'Volume', fadeInL:'Fade In', fadeOutL:'Fade Out', muteL:'Mute',
    analyzeAudio:'Analyze with AI Director', analyzing:'Analyzing audio…', scenes:'Scenes',
    materialsNeeded:'Materials Needed', generateTimeline:'Generate Timeline', improveScene:'Improve Scene',
    regenScene:'Regenerate Scene', hook:'Hook', noAnalysis:'Upload a VTuber video then run AI analysis.',
    uploadVtuber:'Upload VTuber Video (Green Screen)', selectBackground:'Select Background',
    exportMp4:'Export Video (WebM/MP4)', exportXml:'Export Premiere XML (FCPXML)', exportProject:'Export .vtproject',
    exporting:'Exporting…', exportDone:'Export complete', quality:'Quality', highest:'Highest',
    saved:'Project saved', autosaved:'Autosaved', recovered:'Project recovered from autosave',
    deleteConfirm:'Delete this item permanently?', name:'Name', duration:'Duration',
    noClipSelected:'Select a clip on the timeline to edit its properties.',
    trackL:'Track', startL:'Start', endL:'End', transitionIn:'Transition In', transitionOut:'Transition Out',
    animation:'Animation', font:'Font', fontSize:'Font Size', color:'Color', text:'Text',
    activeColor:'Active Word', inactiveColor:'Other Words', outline:'Outline',
    importFont:'Import Font (TTF/OTF)', detectFonts:'Detect System Fonts', template:'Template',
    musicSettings:'Music Mastering', treble:'Treble', needApiKey:'Set your Gemini API key in Settings first.',
    needVtuber:'Upload a VTuber green-screen video first.', ready:'Ready', waiting:'Waiting',
    uploaded:'Uploaded', skipped:'Skipped', missing:'Missing', assignAsset:'Assign',
    aiWorking:'Gemini is directing your video…', timelineGenerated:'Timeline generated by AI Director ✓',
    emotion:'Emotion', energy:'Energy', purpose:'Purpose', score:'Score', editingSpeed:'Editing Speed',
    musicMood:'Music Mood', suggestion:'Suggestion', openEditor:'Open Editor', backToDash:'Back',
    projectSettings:'Project Settings', favorites:'Favorites', recentlyUsed:'Recently Used',
    shortcuts:'Shortcuts', wordsL:'words', clipsL:'clips', addToTimeline:'Add to Timeline',
    setAsBackground:'Set as Background', replaceAsset:'Replace Asset', useAsVtuber:'Use as VTuber',
    extractFromVideo:'Extract from Video', extracting:'Analyzing video…', segmentFound:'Best segment found',
    audioExtracted:'Audio extracted from video ✓', captureFrame:'Frame captured ✓', applyAllCaptions:'Applies to ALL captions',
    noHistory:'No history yet', current:'Current', exportNote:'Browser export renders in real time to WebM (VP9). For H.264 MP4 use the Premiere XML with original assets.',
    downloadFile:'Download', archived:'Archived', archive:'Archive',
  },
  ar: {
    dashboard:'الرئيسية', projects:'المشاريع', editor:'المحرر', materials:'المواد',
    export:'التصدير', settings:'الإعدادات', newProject:'مشروع جديد', importProject:'استيراد مشروع',
    recentProjects:'المشاريع الأخيرة', continueProject:'متابعة', noProjects:'لا توجد مشاريع بعد — أنشئ أول مشروع!',
    projectName:'اسم المشروع', create:'إنشاء', cancel:'إلغاء', save:'حفظ', delete:'حذف',
    duplicate:'نسخ', rename:'إعادة تسمية', open:'فتح', close:'إغلاق', apply:'تطبيق',
    language:'اللغة', apiKey:'مفتاح Gemini API', saveKey:'حفظ المفتاح', testApi:'اختبار الاتصال',
    model:'النموذج', apiOk:'الاتصال بالـ API ناجح ✓', apiFail:'فشل اختبار الـ API',
    keySaved:'تم حفظ المفتاح (مشفّر محليًا)', enterKey:'أدخل مفتاح Gemini API',
    backgrounds:'الخلفيات', music:'الموسيقى', sfx:'المؤثرات الصوتية', memes:'الميمز', images:'الصور', videos:'الفيديوهات',
    upload:'رفع', uploadFiles:'اسحب الملفات هنا أو اضغط للرفع', search:'بحث', skip:'تخطي',
    library:'المكتبة', category:'التصنيف', all:'الكل',
    preview:'المعاينة', timeline:'التايم لاين', properties:'الخصائص', inspector:'الفاحص',
    media:'الوسائط', history:'السجل', ai:'المخرج الذكي', captions:'الترجمة',
    play:'تشغيل', pause:'إيقاف مؤقت', stop:'إيقاف', split:'قص', undo:'تراجع', redo:'إعادة',
    zoomIn:'تكبير', zoomOut:'تصغير', fit:'ملاءمة', snap:'التصاق', safeArea:'المنطقة الآمنة',
    position:'الموضع', scale:'الحجم', rotation:'الدوران', opacity:'الشفافية',
    transform:'التحويل', chromaKey:'كروما كي', tolerance:'التسامح', softness:'نعومة الحواف',
    spill:'إزالة الانعكاس', feather:'التدرّج', blur:'الضبابية', enabled:'مفعّل', keyColor:'لون المفتاح',
    volume:'الصوت', fadeInL:'دخول تدريجي', fadeOutL:'خروج تدريجي', muteL:'كتم',
    analyzeAudio:'تحليل بالمخرج الذكي', analyzing:'جاري تحليل الصوت…', scenes:'المشاهد',
    materialsNeeded:'المواد المطلوبة', generateTimeline:'توليد التايم لاين', improveScene:'تحسين المشهد',
    regenScene:'إعادة توليد المشهد', hook:'الافتتاحية', noAnalysis:'ارفع فيديو الشخصية ثم شغّل التحليل الذكي.',
    uploadVtuber:'رفع فيديو الشخصية (شاشة خضراء)', selectBackground:'اختيار خلفية',
    exportMp4:'تصدير الفيديو (WebM/MP4)', exportXml:'تصدير Premiere XML (FCPXML)', exportProject:'تصدير .vtproject',
    exporting:'جاري التصدير…', exportDone:'اكتمل التصدير', quality:'الجودة', highest:'الأعلى',
    saved:'تم حفظ المشروع', autosaved:'حفظ تلقائي', recovered:'تم استرجاع المشروع من الحفظ التلقائي',
    deleteConfirm:'حذف هذا العنصر نهائيًا؟', name:'الاسم', duration:'المدة',
    noClipSelected:'اختر مقطعًا من التايم لاين لتعديل خصائصه.',
    trackL:'المسار', startL:'البداية', endL:'النهاية', transitionIn:'انتقال الدخول', transitionOut:'انتقال الخروج',
    animation:'الحركة', font:'الخط', fontSize:'حجم الخط', color:'اللون', text:'النص',
    activeColor:'الكلمة الحالية', inactiveColor:'باقي الكلمات', outline:'الحدود',
    importFont:'استيراد خط (TTF/OTF)', detectFonts:'اكتشاف خطوط النظام', template:'القالب',
    musicSettings:'إعدادات الموسيقى', treble:'التريبل', needApiKey:'اضبط مفتاح Gemini في الإعدادات أولًا.',
    needVtuber:'ارفع فيديو الشخصية بالشاشة الخضراء أولًا.', ready:'جاهز', waiting:'بانتظار',
    uploaded:'تم الرفع', skipped:'تم التخطي', missing:'مفقود', assignAsset:'تعيين',
    aiWorking:'Gemini يقوم بإخراج الفيديو…', timelineGenerated:'تم توليد التايم لاين بواسطة المخرج الذكي ✓',
    emotion:'المشاعر', energy:'الطاقة', purpose:'الغرض', score:'التقييم', editingSpeed:'سرعة المونتاج',
    musicMood:'مزاج الموسيقى', suggestion:'اقتراح', openEditor:'فتح المحرر', backToDash:'رجوع',
    projectSettings:'إعدادات المشروع', favorites:'المفضلة', recentlyUsed:'المستخدمة مؤخرًا',
    shortcuts:'الاختصارات', wordsL:'كلمة', clipsL:'مقطع', addToTimeline:'إضافة للتايم لاين',
    setAsBackground:'تعيين كخلفية', replaceAsset:'استبدال الملف', useAsVtuber:'استخدام كشخصية',
    extractFromVideo:'استخراج من فيديو', extracting:'جاري تحليل الفيديو…', segmentFound:'تم إيجاد أفضل لقطة',
    audioExtracted:'تم استخراج الصوت من الفيديو ✓', captureFrame:'تم التقاط الفريم ✓', applyAllCaptions:'يطبّق على كل الكبشن',
    noHistory:'لا يوجد سجل بعد', current:'الحالي', exportNote:'التصدير من المتصفح يتم بالوقت الحقيقي إلى WebM (VP9). لتصدير MP4 بجودة H.264 استخدم ملف Premiere XML مع الملفات الأصلية.',
    downloadFile:'تنزيل', archived:'مؤرشف', archive:'أرشفة',
  },
};

let lang = localStorage.getItem('vt_lang') || 'ar';

export function t(key) { return dict[lang]?.[key] ?? dict.en[key] ?? key; }
export function getLang() { return lang; }
export function setLang(l) {
  lang = l;
  localStorage.setItem('vt_lang', l);
  document.documentElement.lang = l;
  document.documentElement.dir = l === 'ar' ? 'rtl' : 'ltr';
  window.dispatchEvent(new CustomEvent('langchange'));
}
export function initLang() {
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
}
export function trackName(track) { return track.name[lang] ?? track.name.en; }
